/* Generated by Yosys 0.52 (git sha1 fee39a3284c90249e1d9684cf6944ffbbcbb8f90) */

(* src = "rtl/modules/adder_4bit.v:7.1-34.10" *)
module adder_4bit(a, b, sub, result, cout, overflow);
  (* src = "rtl/modules/adder_4bit.v:8.23-8.24" *)
  input [3:0] a;
  wire [3:0] a;
  (* src = "rtl/modules/adder_4bit.v:9.23-9.24" *)
  input [3:0] b;
  wire [3:0] b;
  (* src = "rtl/modules/adder_4bit.v:21.16-21.20" *)
  wire [3:0] b_in;
  (* src = "rtl/modules/adder_4bit.v:17.10-17.12" *)
  wire c1;
  (* src = "rtl/modules/adder_4bit.v:17.14-17.16" *)
  wire c2;
  (* src = "rtl/modules/adder_4bit.v:17.18-17.20" *)
  wire c3;
  (* src = "rtl/modules/adder_4bit.v:12.23-12.27" *)
  output cout;
  wire cout;
  (* src = "rtl/modules/adder_4bit.v:13.23-13.31" *)
  output overflow;
  wire overflow;
  (* src = "rtl/modules/adder_4bit.v:11.23-11.29" *)
  output [3:0] result;
  wire [3:0] result;
  (* src = "rtl/modules/adder_4bit.v:10.23-10.26" *)
  input sub;
  wire sub;
  assign b_in[0] = b[0] ^(* src = "rtl/modules/adder_4bit.v:22.19-22.31" *)  sub;
  assign b_in[1] = b[1] ^(* src = "rtl/modules/adder_4bit.v:22.19-22.31" *)  sub;
  assign b_in[2] = b[2] ^(* src = "rtl/modules/adder_4bit.v:22.19-22.31" *)  sub;
  assign b_in[3] = b[3] ^(* src = "rtl/modules/adder_4bit.v:22.19-22.31" *)  sub;
  assign overflow = c3 ^(* src = "rtl/modules/adder_4bit.v:32.23-32.32" *)  cout;
  (* module_not_derived = 32'd1 *)
  (* src = "rtl/modules/adder_4bit.v:26.16-26.83" *)
  full_adder FA0 (
    .a(a[0]),
    .b(b_in[0]),
    .cin(sub),
    .cout(c1),
    .sum(result[0])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "rtl/modules/adder_4bit.v:27.16-27.83" *)
  full_adder FA1 (
    .a(a[1]),
    .b(b_in[1]),
    .cin(c1),
    .cout(c2),
    .sum(result[1])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "rtl/modules/adder_4bit.v:28.16-28.83" *)
  full_adder FA2 (
    .a(a[2]),
    .b(b_in[2]),
    .cin(c2),
    .cout(c3),
    .sum(result[2])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "rtl/modules/adder_4bit.v:29.16-29.85" *)
  full_adder FA3 (
    .a(a[3]),
    .b(b_in[3]),
    .cin(c3),
    .cout(cout),
    .sum(result[3])
  );
endmodule

(* top =  1  *)
(* src = "rtl/top/alu_4bit.v:8.1-131.10" *)
module alu_4bit(a, b, opcode, result, zero, carry, overflow, negative);
  (* src = "rtl/top/alu_4bit.v:112.33-112.38" *)
  wire [3:0] _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire [1:0] _006_;
  wire _007_;
  wire [1:0] _008_;
  wire [1:0] _009_;
  wire [1:0] _010_;
  wire [1:0] _011_;
  wire [1:0] _012_;
  wire [1:0] _013_;
  wire [1:0] _014_;
  wire [1:0] _015_;
  wire [4:0] _016_;
  wire [2:0] _017_;
  wire _018_;
  wire [3:0] _019_;
  wire [1:0] _020_;
  wire _021_;
  wire [2:0] _022_;
  wire [1:0] _023_;
  wire [2:0] _024_;
  wire [1:0] _025_;
  wire [2:0] _026_;
  wire [1:0] _027_;
  wire [2:0] _028_;
  wire [1:0] _029_;
  wire [2:0] _030_;
  wire [1:0] _031_;
  wire [1:0] _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  (* src = "rtl/top/alu_4bit.v:52.22-52.38" *)
  wire _050_;
  (* src = "rtl/top/alu_4bit.v:52.44-52.60" *)
  wire _051_;
  (* src = "rtl/top/alu_4bit.v:52.66-52.82" *)
  wire _052_;
  (* src = "rtl/top/alu_4bit.v:55.24-55.40" *)
  wire _053_;
  (* src = "rtl/top/alu_4bit.v:58.25-58.41" *)
  wire _054_;
  (* src = "rtl/top/alu_4bit.v:59.25-59.40" *)
  wire _055_;
  (* src = "rtl/top/alu_4bit.v:60.25-60.41" *)
  wire _056_;
  (* src = "rtl/top/alu_4bit.v:63.25-63.41" *)
  wire _057_;
  (* src = "rtl/top/alu_4bit.v:64.25-64.41" *)
  wire _058_;
  (* src = "rtl/top/alu_4bit.v:65.25-65.41" *)
  wire _059_;
  (* src = "rtl/top/alu_4bit.v:55.23-55.63" *)
  wire _060_;
  (* src = "rtl/top/alu_4bit.v:113.33-113.38" *)
  wire [3:0] _061_;
  (* force_downto = 32'd1 *)
  (* src = "rtl/top/alu_4bit.v:0.0-0.0|rtl/top/alu_4bit.v:100.9-124.16|/usr/bin/../share/yosys/techmap.v:584.28-584.35" *)
  wire [1:0] _062_;
  (* force_downto = 32'd1 *)
  (* src = "rtl/top/alu_4bit.v:0.0-0.0|rtl/top/alu_4bit.v:100.9-124.16|/usr/bin/../share/yosys/techmap.v:574.22-574.23" *)
  wire [1:0] _063_;
  wire _064_;
  wire [4:0] _065_;
  (* force_downto = 32'd1 *)
  (* src = "rtl/top/alu_4bit.v:0.0-0.0|rtl/top/alu_4bit.v:100.9-124.16|/usr/bin/../share/yosys/techmap.v:584.28-584.35" *)
  wire [2:0] _066_;
  (* force_downto = 32'd1 *)
  (* src = "rtl/top/alu_4bit.v:0.0-0.0|rtl/top/alu_4bit.v:100.9-124.16|/usr/bin/../share/yosys/techmap.v:574.22-574.23" *)
  wire [2:0] _067_;
  (* force_downto = 32'd1 *)
  (* src = "rtl/top/alu_4bit.v:0.0-0.0|rtl/top/alu_4bit.v:100.9-124.16|/usr/bin/../share/yosys/techmap.v:579.19-579.22" *)
  wire _068_;
  (* force_downto = 32'd1 *)
  (* src = "rtl/top/alu_4bit.v:0.0-0.0|rtl/top/alu_4bit.v:100.9-124.16|/usr/bin/../share/yosys/techmap.v:572.28-572.29" *)
  wire [27:0] _069_;
  (* force_downto = 32'd1 *)
  (* src = "rtl/top/alu_4bit.v:0.0-0.0|rtl/top/alu_4bit.v:100.9-124.16|/usr/bin/../share/yosys/techmap.v:584.28-584.35" *)
  wire [27:0] _070_;
  (* force_downto = 32'd1 *)
  (* src = "rtl/top/alu_4bit.v:0.0-0.0|rtl/top/alu_4bit.v:100.9-124.16|/usr/bin/../share/yosys/techmap.v:574.22-574.23" *)
  wire [6:0] _071_;
  (* force_downto = 32'd1 *)
  (* src = "rtl/top/alu_4bit.v:0.0-0.0|rtl/top/alu_4bit.v:100.9-124.16|/usr/bin/../share/yosys/techmap.v:579.19-579.22" *)
  wire [3:0] _072_;
  (* src = "rtl/top/alu_4bit.v:0.0-0.0|rtl/top/alu_4bit.v:100.9-124.16|/usr/bin/../share/yosys/techmap.v:598.13-598.15" *)
  wire _073_;
  (* src = "rtl/top/alu_4bit.v:0.0-0.0|rtl/top/alu_4bit.v:100.9-124.16|/usr/bin/../share/yosys/techmap.v:598.13-598.15" *)
  wire _074_;
  (* src = "rtl/top/alu_4bit.v:0.0-0.0|rtl/top/alu_4bit.v:100.9-124.16|/usr/bin/../share/yosys/techmap.v:598.13-598.15" *)
  wire _075_;
  (* src = "rtl/top/alu_4bit.v:59.24-60.79" *)
  wire [1:0] _076_;
  (* src = "rtl/top/alu_4bit.v:60.24-60.79" *)
  wire [1:0] _077_;
  (* src = "rtl/top/alu_4bit.v:64.24-65.58" *)
  wire [1:0] _078_;
  (* src = "rtl/top/alu_4bit.v:114.33-114.38" *)
  wire [3:0] _079_;
  (* src = "rtl/top/alu_4bit.v:9.23-9.24" *)
  input [3:0] a;
  wire [3:0] a;
  (* src = "rtl/top/alu_4bit.v:39.16-39.26" *)
  wire arith_cout;
  (* src = "rtl/top/alu_4bit.v:40.16-40.30" *)
  wire arith_overflow;
  (* src = "rtl/top/alu_4bit.v:38.16-38.28" *)
  wire [3:0] arith_result;
  (* src = "rtl/top/alu_4bit.v:10.23-10.24" *)
  input [3:0] b;
  wire [3:0] b;
  (* src = "rtl/top/alu_4bit.v:47.16-47.23" *)
  wire [3:0] b_arith;
  (* src = "rtl/top/alu_4bit.v:14.23-14.28" *)
  output carry;
  wire carry;
  (* src = "rtl/top/alu_4bit.v:41.16-41.28" *)
  wire [3:0] logic_result;
  (* src = "rtl/top/alu_4bit.v:48.16-48.25" *)
  wire [1:0] logic_sel;
  (* src = "rtl/top/alu_4bit.v:16.23-16.31" *)
  output negative;
  wire negative;
  (* src = "rtl/top/alu_4bit.v:11.23-11.29" *)
  input [3:0] opcode;
  wire [3:0] opcode;
  (* src = "rtl/top/alu_4bit.v:15.23-15.31" *)
  output overflow;
  wire overflow;
  (* src = "rtl/top/alu_4bit.v:12.23-12.29" *)
  output [3:0] result;
  wire [3:0] result;
  (* src = "rtl/top/alu_4bit.v:43.16-43.27" *)
  wire shift_carry;
  (* src = "rtl/top/alu_4bit.v:42.16-42.28" *)
  wire [3:0] shift_result;
  (* src = "rtl/top/alu_4bit.v:49.16-49.25" *)
  wire [1:0] shift_sel;
  (* src = "rtl/top/alu_4bit.v:46.10-46.16" *)
  wire sub_op;
  (* src = "rtl/top/alu_4bit.v:13.23-13.27" *)
  output zero;
  wire zero;
  assign _001_ = ~opcode[0];
  assign _002_ = ~opcode[1];
  assign _003_ = ~opcode[2];
  assign _004_ = ~opcode[3];
  assign _067_[1] = _005_ |(* src = "rtl/top/alu_4bit.v:0.0-0.0|rtl/top/alu_4bit.v:100.9-124.16" *)  _059_;
  assign _006_[0] = _050_ |(* src = "rtl/top/alu_4bit.v:0.0-0.0|rtl/top/alu_4bit.v:100.9-124.16" *)  _051_;
  assign _006_[1] = _052_ |(* src = "rtl/top/alu_4bit.v:0.0-0.0|rtl/top/alu_4bit.v:100.9-124.16" *)  _053_;
  assign _007_ = _006_[0] |(* src = "rtl/top/alu_4bit.v:0.0-0.0|rtl/top/alu_4bit.v:100.9-124.16" *)  _006_[1];
  assign _063_[1] = _007_ |(* src = "rtl/top/alu_4bit.v:0.0-0.0|rtl/top/alu_4bit.v:100.9-124.16" *)  _065_[0];
  assign _035_ = _008_[0] |(* src = "rtl/top/alu_4bit.v:0.0-0.0|rtl/top/alu_4bit.v:100.9-124.16" *)  _008_[1];
  assign _036_ = _008_[0] |(* src = "rtl/top/alu_4bit.v:0.0-0.0|rtl/top/alu_4bit.v:100.9-124.16" *)  _009_[1];
  assign _037_ = _010_[0] |(* src = "rtl/top/alu_4bit.v:0.0-0.0|rtl/top/alu_4bit.v:100.9-124.16" *)  _008_[1];
  assign _008_[1] = _003_ |(* src = "rtl/top/alu_4bit.v:0.0-0.0|rtl/top/alu_4bit.v:100.9-124.16" *)  _004_;
  assign _038_ = _011_[0] |(* src = "rtl/top/alu_4bit.v:0.0-0.0|rtl/top/alu_4bit.v:100.9-124.16" *)  _008_[1];
  assign _039_ = _012_[0] |(* src = "rtl/top/alu_4bit.v:0.0-0.0|rtl/top/alu_4bit.v:100.9-124.16" *)  _009_[1];
  assign _040_ = _011_[0] |(* src = "rtl/top/alu_4bit.v:0.0-0.0|rtl/top/alu_4bit.v:100.9-124.16" *)  _009_[1];
  assign _009_[1] = opcode[2] |(* src = "rtl/top/alu_4bit.v:0.0-0.0|rtl/top/alu_4bit.v:100.9-124.16" *)  _004_;
  assign _041_ = _010_[0] |(* src = "rtl/top/alu_4bit.v:0.0-0.0|rtl/top/alu_4bit.v:100.9-124.16" *)  _009_[1];
  assign _008_[0] = _001_ |(* src = "rtl/top/alu_4bit.v:0.0-0.0|rtl/top/alu_4bit.v:100.9-124.16" *)  _002_;
  assign _042_ = _008_[0] |(* src = "rtl/top/alu_4bit.v:0.0-0.0|rtl/top/alu_4bit.v:100.9-124.16" *)  _013_[1];
  assign _043_ = _012_[0] |(* src = "rtl/top/alu_4bit.v:0.0-0.0|rtl/top/alu_4bit.v:100.9-124.16" *)  _013_[1];
  assign _044_ = _011_[0] |(* src = "rtl/top/alu_4bit.v:0.0-0.0|rtl/top/alu_4bit.v:100.9-124.16" *)  _013_[1];
  assign _013_[1] = _003_ |(* src = "rtl/top/alu_4bit.v:0.0-0.0|rtl/top/alu_4bit.v:100.9-124.16" *)  opcode[3];
  assign _045_ = _010_[0] |(* src = "rtl/top/alu_4bit.v:0.0-0.0|rtl/top/alu_4bit.v:100.9-124.16" *)  _013_[1];
  assign _011_[0] = _001_ |(* src = "rtl/top/alu_4bit.v:0.0-0.0|rtl/top/alu_4bit.v:100.9-124.16" *)  opcode[1];
  assign _046_ = _011_[0] |(* src = "rtl/top/alu_4bit.v:0.0-0.0|rtl/top/alu_4bit.v:100.9-124.16" *)  _014_[1];
  assign _012_[0] = opcode[0] |(* src = "rtl/top/alu_4bit.v:0.0-0.0|rtl/top/alu_4bit.v:100.9-124.16" *)  _002_;
  assign _047_ = _012_[0] |(* src = "rtl/top/alu_4bit.v:0.0-0.0|rtl/top/alu_4bit.v:100.9-124.16" *)  _014_[1];
  assign _014_[1] = opcode[2] |(* src = "rtl/top/alu_4bit.v:0.0-0.0|rtl/top/alu_4bit.v:100.9-124.16" *)  opcode[3];
  assign _048_ = _008_[0] |(* src = "rtl/top/alu_4bit.v:0.0-0.0|rtl/top/alu_4bit.v:100.9-124.16" *)  _014_[1];
  assign _049_ = _012_[0] |(* src = "rtl/top/alu_4bit.v:0.0-0.0|rtl/top/alu_4bit.v:100.9-124.16" *)  _008_[1];
  assign _015_[0] = _054_ |(* src = {0{1'b0}} *)  _055_;
  assign _015_[1] = _056_ |(* src = {0{1'b0}} *)  _064_;
  assign _071_[5] = _015_[0] |(* src = {0{1'b0}} *)  _015_[1];
  assign _005_ = _057_ |(* src = {0{1'b0}} *)  _058_;
  assign _016_[4] = _059_ |(* src = {0{1'b0}} *)  _071_[0];
  assign _017_[1] = _016_[2] |(* src = {0{1'b0}} *)  _005_;
  assign _017_[2] = _016_[4] |(* src = {0{1'b0}} *)  _064_;
  assign _018_ = _017_[0] |(* src = {0{1'b0}} *)  _017_[1];
  assign _063_[0] = _018_ |(* src = {0{1'b0}} *)  _017_[2];
  assign _016_[0] = _054_ |(* src = {0{1'b0}} *)  _071_[4];
  assign _016_[1] = _055_ |(* src = {0{1'b0}} *)  _071_[3];
  assign _016_[2] = _056_ |(* src = {0{1'b0}} *)  _071_[2];
  assign _019_[3] = _071_[0] |(* src = {0{1'b0}} *)  _064_;
  assign _017_[0] = _016_[0] |(* src = {0{1'b0}} *)  _016_[1];
  assign _020_[1] = _016_[2] |(* src = {0{1'b0}} *)  _019_[3];
  assign _067_[0] = _017_[0] |(* src = {0{1'b0}} *)  _020_[1];
  assign _073_ = _063_[0] |(* src = "rtl/top/alu_4bit.v:0.0-0.0|rtl/top/alu_4bit.v:100.9-124.16|/usr/bin/../share/yosys/techmap.v:598.13-598.15" *)  _063_[1];
  assign _068_ = _066_[1] |(* src = "rtl/top/alu_4bit.v:0.0-0.0|rtl/top/alu_4bit.v:100.9-124.16|/usr/bin/../share/yosys/techmap.v:594.20-594.31" *)  _066_[2];
  assign _021_ = _067_[0] |(* src = "rtl/top/alu_4bit.v:0.0-0.0|rtl/top/alu_4bit.v:100.9-124.16|/usr/bin/../share/yosys/techmap.v:598.13-598.15" *)  _067_[1];
  assign _074_ = _021_ |(* src = "rtl/top/alu_4bit.v:0.0-0.0|rtl/top/alu_4bit.v:100.9-124.16|/usr/bin/../share/yosys/techmap.v:598.13-598.15" *)  _063_[1];
  assign _022_[0] = _070_[3] |(* src = "rtl/top/alu_4bit.v:0.0-0.0|rtl/top/alu_4bit.v:100.9-124.16|/usr/bin/../share/yosys/techmap.v:594.20-594.31" *)  _070_[7];
  assign _022_[1] = _070_[11] |(* src = "rtl/top/alu_4bit.v:0.0-0.0|rtl/top/alu_4bit.v:100.9-124.16|/usr/bin/../share/yosys/techmap.v:594.20-594.31" *)  _070_[15];
  assign _022_[2] = _070_[19] |(* src = "rtl/top/alu_4bit.v:0.0-0.0|rtl/top/alu_4bit.v:100.9-124.16|/usr/bin/../share/yosys/techmap.v:594.20-594.31" *)  _070_[23];
  assign _023_[0] = _022_[0] |(* src = "rtl/top/alu_4bit.v:0.0-0.0|rtl/top/alu_4bit.v:100.9-124.16|/usr/bin/../share/yosys/techmap.v:594.20-594.31" *)  _022_[1];
  assign _023_[1] = _022_[2] |(* src = "rtl/top/alu_4bit.v:0.0-0.0|rtl/top/alu_4bit.v:100.9-124.16|/usr/bin/../share/yosys/techmap.v:594.20-594.31" *)  _070_[27];
  assign _072_[3] = _023_[0] |(* src = "rtl/top/alu_4bit.v:0.0-0.0|rtl/top/alu_4bit.v:100.9-124.16|/usr/bin/../share/yosys/techmap.v:594.20-594.31" *)  _023_[1];
  assign _024_[0] = _070_[2] |(* src = "rtl/top/alu_4bit.v:0.0-0.0|rtl/top/alu_4bit.v:100.9-124.16|/usr/bin/../share/yosys/techmap.v:594.20-594.31" *)  _070_[6];
  assign _024_[1] = _070_[10] |(* src = "rtl/top/alu_4bit.v:0.0-0.0|rtl/top/alu_4bit.v:100.9-124.16|/usr/bin/../share/yosys/techmap.v:594.20-594.31" *)  _070_[14];
  assign _024_[2] = _070_[18] |(* src = "rtl/top/alu_4bit.v:0.0-0.0|rtl/top/alu_4bit.v:100.9-124.16|/usr/bin/../share/yosys/techmap.v:594.20-594.31" *)  _070_[22];
  assign _025_[0] = _024_[0] |(* src = "rtl/top/alu_4bit.v:0.0-0.0|rtl/top/alu_4bit.v:100.9-124.16|/usr/bin/../share/yosys/techmap.v:594.20-594.31" *)  _024_[1];
  assign _025_[1] = _024_[2] |(* src = "rtl/top/alu_4bit.v:0.0-0.0|rtl/top/alu_4bit.v:100.9-124.16|/usr/bin/../share/yosys/techmap.v:594.20-594.31" *)  _070_[26];
  assign _072_[2] = _025_[0] |(* src = "rtl/top/alu_4bit.v:0.0-0.0|rtl/top/alu_4bit.v:100.9-124.16|/usr/bin/../share/yosys/techmap.v:594.20-594.31" *)  _025_[1];
  assign _026_[0] = _070_[1] |(* src = "rtl/top/alu_4bit.v:0.0-0.0|rtl/top/alu_4bit.v:100.9-124.16|/usr/bin/../share/yosys/techmap.v:594.20-594.31" *)  _070_[5];
  assign _026_[1] = _070_[9] |(* src = "rtl/top/alu_4bit.v:0.0-0.0|rtl/top/alu_4bit.v:100.9-124.16|/usr/bin/../share/yosys/techmap.v:594.20-594.31" *)  _070_[13];
  assign _026_[2] = _070_[17] |(* src = "rtl/top/alu_4bit.v:0.0-0.0|rtl/top/alu_4bit.v:100.9-124.16|/usr/bin/../share/yosys/techmap.v:594.20-594.31" *)  _070_[21];
  assign _027_[0] = _026_[0] |(* src = "rtl/top/alu_4bit.v:0.0-0.0|rtl/top/alu_4bit.v:100.9-124.16|/usr/bin/../share/yosys/techmap.v:594.20-594.31" *)  _026_[1];
  assign _027_[1] = _026_[2] |(* src = "rtl/top/alu_4bit.v:0.0-0.0|rtl/top/alu_4bit.v:100.9-124.16|/usr/bin/../share/yosys/techmap.v:594.20-594.31" *)  _070_[25];
  assign _072_[1] = _027_[0] |(* src = "rtl/top/alu_4bit.v:0.0-0.0|rtl/top/alu_4bit.v:100.9-124.16|/usr/bin/../share/yosys/techmap.v:594.20-594.31" *)  _027_[1];
  assign _028_[0] = _070_[0] |(* src = "rtl/top/alu_4bit.v:0.0-0.0|rtl/top/alu_4bit.v:100.9-124.16|/usr/bin/../share/yosys/techmap.v:594.20-594.31" *)  _070_[4];
  assign _028_[1] = _070_[8] |(* src = "rtl/top/alu_4bit.v:0.0-0.0|rtl/top/alu_4bit.v:100.9-124.16|/usr/bin/../share/yosys/techmap.v:594.20-594.31" *)  _070_[12];
  assign _028_[2] = _070_[16] |(* src = "rtl/top/alu_4bit.v:0.0-0.0|rtl/top/alu_4bit.v:100.9-124.16|/usr/bin/../share/yosys/techmap.v:594.20-594.31" *)  _070_[20];
  assign _029_[0] = _028_[0] |(* src = "rtl/top/alu_4bit.v:0.0-0.0|rtl/top/alu_4bit.v:100.9-124.16|/usr/bin/../share/yosys/techmap.v:594.20-594.31" *)  _028_[1];
  assign _029_[1] = _028_[2] |(* src = "rtl/top/alu_4bit.v:0.0-0.0|rtl/top/alu_4bit.v:100.9-124.16|/usr/bin/../share/yosys/techmap.v:594.20-594.31" *)  _070_[24];
  assign _072_[0] = _029_[0] |(* src = "rtl/top/alu_4bit.v:0.0-0.0|rtl/top/alu_4bit.v:100.9-124.16|/usr/bin/../share/yosys/techmap.v:594.20-594.31" *)  _029_[1];
  assign _030_[0] = _071_[0] |(* src = "rtl/top/alu_4bit.v:0.0-0.0|rtl/top/alu_4bit.v:100.9-124.16|/usr/bin/../share/yosys/techmap.v:598.13-598.15" *)  _067_[1];
  assign _030_[1] = _071_[2] |(* src = "rtl/top/alu_4bit.v:0.0-0.0|rtl/top/alu_4bit.v:100.9-124.16|/usr/bin/../share/yosys/techmap.v:598.13-598.15" *)  _071_[3];
  assign _030_[2] = _071_[4] |(* src = "rtl/top/alu_4bit.v:0.0-0.0|rtl/top/alu_4bit.v:100.9-124.16|/usr/bin/../share/yosys/techmap.v:598.13-598.15" *)  _071_[5];
  assign _031_[0] = _030_[0] |(* src = "rtl/top/alu_4bit.v:0.0-0.0|rtl/top/alu_4bit.v:100.9-124.16|/usr/bin/../share/yosys/techmap.v:598.13-598.15" *)  _030_[1];
  assign _031_[1] = _030_[2] |(* src = "rtl/top/alu_4bit.v:0.0-0.0|rtl/top/alu_4bit.v:100.9-124.16|/usr/bin/../share/yosys/techmap.v:598.13-598.15" *)  _063_[1];
  assign _075_ = _031_[0] |(* src = "rtl/top/alu_4bit.v:0.0-0.0|rtl/top/alu_4bit.v:100.9-124.16|/usr/bin/../share/yosys/techmap.v:598.13-598.15" *)  _031_[1];
  assign _032_[0] = result[0] |(* src = "rtl/top/alu_4bit.v:127.21-127.38" *)  result[1];
  assign _032_[1] = result[2] |(* src = "rtl/top/alu_4bit.v:127.21-127.38" *)  negative;
  assign _033_ = _032_[0] |(* src = "rtl/top/alu_4bit.v:127.21-127.38" *)  _032_[1];
  assign _010_[0] = opcode[0] |(* src = "rtl/top/alu_4bit.v:0.0-0.0|rtl/top/alu_4bit.v:100.9-124.16" *)  opcode[1];
  assign _034_ = _010_[0] |(* src = "rtl/top/alu_4bit.v:0.0-0.0|rtl/top/alu_4bit.v:100.9-124.16" *)  _014_[1];
  assign zero = ~(* src = "rtl/top/alu_4bit.v:127.21-127.38" *) _033_;
  assign _071_[0] = ~(* src = "rtl/top/alu_4bit.v:0.0-0.0|rtl/top/alu_4bit.v:100.9-124.16" *) _035_;
  assign _057_ = ~(* src = "rtl/top/alu_4bit.v:0.0-0.0|rtl/top/alu_4bit.v:100.9-124.16" *) _036_;
  assign _058_ = ~(* src = "rtl/top/alu_4bit.v:0.0-0.0|rtl/top/alu_4bit.v:100.9-124.16" *) _037_;
  assign _059_ = ~(* src = "rtl/top/alu_4bit.v:0.0-0.0|rtl/top/alu_4bit.v:100.9-124.16" *) _038_;
  assign _071_[2] = ~(* src = "rtl/top/alu_4bit.v:0.0-0.0|rtl/top/alu_4bit.v:100.9-124.16" *) _039_;
  assign _071_[3] = ~(* src = "rtl/top/alu_4bit.v:0.0-0.0|rtl/top/alu_4bit.v:100.9-124.16" *) _040_;
  assign _071_[4] = ~(* src = "rtl/top/alu_4bit.v:0.0-0.0|rtl/top/alu_4bit.v:100.9-124.16" *) _041_;
  assign _064_ = ~(* src = "rtl/top/alu_4bit.v:0.0-0.0|rtl/top/alu_4bit.v:100.9-124.16" *) _042_;
  assign _056_ = ~(* src = "rtl/top/alu_4bit.v:0.0-0.0|rtl/top/alu_4bit.v:100.9-124.16" *) _043_;
  assign _055_ = ~(* src = "rtl/top/alu_4bit.v:0.0-0.0|rtl/top/alu_4bit.v:100.9-124.16" *) _044_;
  assign _054_ = ~(* src = "rtl/top/alu_4bit.v:0.0-0.0|rtl/top/alu_4bit.v:100.9-124.16" *) _045_;
  assign _065_[0] = ~(* src = "rtl/top/alu_4bit.v:0.0-0.0|rtl/top/alu_4bit.v:100.9-124.16" *) _034_;
  assign _050_ = ~(* src = "rtl/top/alu_4bit.v:0.0-0.0|rtl/top/alu_4bit.v:100.9-124.16" *) _046_;
  assign _053_ = ~(* src = "rtl/top/alu_4bit.v:0.0-0.0|rtl/top/alu_4bit.v:100.9-124.16" *) _047_;
  assign _051_ = ~(* src = "rtl/top/alu_4bit.v:0.0-0.0|rtl/top/alu_4bit.v:100.9-124.16" *) _048_;
  assign _052_ = ~(* src = "rtl/top/alu_4bit.v:0.0-0.0|rtl/top/alu_4bit.v:100.9-124.16" *) _049_;
  assign sub_op = _006_[0] |(* src = "rtl/top/alu_4bit.v:52.21-52.83" *)  _052_;
  assign _060_ = _053_ |(* src = "rtl/top/alu_4bit.v:55.23-55.63" *)  _051_;
  assign b_arith[0] = _060_ ? (* src = "rtl/top/alu_4bit.v:55.22-55.78" *) 1'h1 : b[0];
  assign b_arith[1] = _060_ ? (* src = "rtl/top/alu_4bit.v:55.22-55.78" *) 1'h0 : b[1];
  assign b_arith[2] = _060_ ? (* src = "rtl/top/alu_4bit.v:55.22-55.78" *) 1'h0 : b[2];
  assign b_arith[3] = _060_ ? (* src = "rtl/top/alu_4bit.v:55.22-55.78" *) 1'h0 : b[3];
  assign _077_[0] = ~(* src = "rtl/top/alu_4bit.v:60.24-60.79" *) _016_[2];
  assign _076_[0] = _016_[1] ? (* src = "rtl/top/alu_4bit.v:59.24-60.79" *) 1'h1 : _077_[0];
  assign _076_[1] = ~(* src = "rtl/top/alu_4bit.v:59.24-60.79" *) _016_[1];
  assign logic_sel[0] = _016_[0] ? (* src = "rtl/top/alu_4bit.v:58.24-60.79" *) 1'h0 : _076_[0];
  assign logic_sel[1] = _016_[0] ? (* src = "rtl/top/alu_4bit.v:58.24-60.79" *) 1'h0 : _076_[1];
  assign _078_[0] = _037_ ? (* src = "rtl/top/alu_4bit.v:64.24-65.58" *) _038_ : 1'h1;
  assign shift_sel[0] = _036_ ? (* src = "rtl/top/alu_4bit.v:63.24-65.58" *) _078_[0] : 1'h0;
  assign shift_sel[1] = _036_ ? (* src = "rtl/top/alu_4bit.v:63.24-65.58" *) _037_ : 1'h0;
  assign overflow = _073_ ? (* src = "rtl/top/alu_4bit.v:0.0-0.0|rtl/top/alu_4bit.v:100.9-124.16|/usr/bin/../share/yosys/techmap.v:598.13-598.25" *) _062_[1] : 1'hx;
  assign carry = _074_ ? (* src = "rtl/top/alu_4bit.v:0.0-0.0|rtl/top/alu_4bit.v:100.9-124.16|/usr/bin/../share/yosys/techmap.v:598.13-598.25" *) _068_ : 1'hx;
  assign result[0] = _075_ ? (* src = "rtl/top/alu_4bit.v:0.0-0.0|rtl/top/alu_4bit.v:100.9-124.16|/usr/bin/../share/yosys/techmap.v:598.13-598.25" *) _072_[0] : 1'hx;
  assign result[1] = _075_ ? (* src = "rtl/top/alu_4bit.v:0.0-0.0|rtl/top/alu_4bit.v:100.9-124.16|/usr/bin/../share/yosys/techmap.v:598.13-598.25" *) _072_[1] : 1'hx;
  assign result[2] = _075_ ? (* src = "rtl/top/alu_4bit.v:0.0-0.0|rtl/top/alu_4bit.v:100.9-124.16|/usr/bin/../share/yosys/techmap.v:598.13-598.25" *) _072_[2] : 1'hx;
  assign negative = _075_ ? (* src = "rtl/top/alu_4bit.v:0.0-0.0|rtl/top/alu_4bit.v:100.9-124.16|/usr/bin/../share/yosys/techmap.v:598.13-598.25" *) _072_[3] : 1'hx;
  assign _069_[16] = ~(* src = "rtl/top/alu_4bit.v:112.31-112.39" *) _000_[0];
  assign _069_[17] = ~(* src = "rtl/top/alu_4bit.v:112.31-112.39" *) _000_[1];
  assign _069_[18] = ~(* src = "rtl/top/alu_4bit.v:112.31-112.39" *) _000_[2];
  assign _069_[19] = ~(* src = "rtl/top/alu_4bit.v:112.31-112.39" *) _000_[3];
  assign _069_[12] = ~(* src = "rtl/top/alu_4bit.v:113.31-113.39" *) _061_[0];
  assign _069_[13] = ~(* src = "rtl/top/alu_4bit.v:113.31-113.39" *) _061_[1];
  assign _069_[14] = ~(* src = "rtl/top/alu_4bit.v:113.31-113.39" *) _061_[2];
  assign _069_[15] = ~(* src = "rtl/top/alu_4bit.v:113.31-113.39" *) _061_[3];
  assign _069_[8] = ~(* src = "rtl/top/alu_4bit.v:114.31-114.39" *) _079_[0];
  assign _069_[9] = ~(* src = "rtl/top/alu_4bit.v:114.31-114.39" *) _079_[1];
  assign _069_[10] = ~(* src = "rtl/top/alu_4bit.v:114.31-114.39" *) _079_[2];
  assign _069_[11] = ~(* src = "rtl/top/alu_4bit.v:114.31-114.39" *) _079_[3];
  assign _000_[0] = a[0] &(* src = "rtl/top/alu_4bit.v:112.33-112.38" *)  b[0];
  assign _000_[1] = a[1] &(* src = "rtl/top/alu_4bit.v:112.33-112.38" *)  b[1];
  assign _000_[2] = a[2] &(* src = "rtl/top/alu_4bit.v:112.33-112.38" *)  b[2];
  assign _000_[3] = a[3] &(* src = "rtl/top/alu_4bit.v:112.33-112.38" *)  b[3];
  assign _061_[0] = a[0] |(* src = "rtl/top/alu_4bit.v:113.33-113.38" *)  b[0];
  assign _061_[1] = a[1] |(* src = "rtl/top/alu_4bit.v:113.33-113.38" *)  b[1];
  assign _061_[2] = a[2] |(* src = "rtl/top/alu_4bit.v:113.33-113.38" *)  b[2];
  assign _061_[3] = a[3] |(* src = "rtl/top/alu_4bit.v:113.33-113.38" *)  b[3];
  assign _079_[0] = a[0] ^(* src = "rtl/top/alu_4bit.v:114.33-114.38" *)  b[0];
  assign _079_[1] = a[1] ^(* src = "rtl/top/alu_4bit.v:114.33-114.38" *)  b[1];
  assign _079_[2] = a[2] ^(* src = "rtl/top/alu_4bit.v:114.33-114.38" *)  b[2];
  assign _079_[3] = a[3] ^(* src = "rtl/top/alu_4bit.v:114.33-114.38" *)  b[3];
  assign _062_[1] = arith_overflow &(* src = "rtl/top/alu_4bit.v:0.0-0.0|rtl/top/alu_4bit.v:100.9-124.16|/usr/bin/../share/yosys/techmap.v:586.44-586.84" *)  _063_[1];
  assign _066_[2] = arith_cout &(* src = "rtl/top/alu_4bit.v:0.0-0.0|rtl/top/alu_4bit.v:100.9-124.16|/usr/bin/../share/yosys/techmap.v:586.44-586.84" *)  _063_[1];
  assign _066_[1] = shift_carry &(* src = "rtl/top/alu_4bit.v:0.0-0.0|rtl/top/alu_4bit.v:100.9-124.16|/usr/bin/../share/yosys/techmap.v:586.44-586.84" *)  _067_[1];
  assign _070_[24] = arith_result[0] &(* src = "rtl/top/alu_4bit.v:0.0-0.0|rtl/top/alu_4bit.v:100.9-124.16|/usr/bin/../share/yosys/techmap.v:586.44-586.84" *)  _063_[1];
  assign _070_[25] = arith_result[1] &(* src = "rtl/top/alu_4bit.v:0.0-0.0|rtl/top/alu_4bit.v:100.9-124.16|/usr/bin/../share/yosys/techmap.v:586.44-586.84" *)  _063_[1];
  assign _070_[26] = arith_result[2] &(* src = "rtl/top/alu_4bit.v:0.0-0.0|rtl/top/alu_4bit.v:100.9-124.16|/usr/bin/../share/yosys/techmap.v:586.44-586.84" *)  _063_[1];
  assign _070_[27] = arith_result[3] &(* src = "rtl/top/alu_4bit.v:0.0-0.0|rtl/top/alu_4bit.v:100.9-124.16|/usr/bin/../share/yosys/techmap.v:586.44-586.84" *)  _063_[1];
  assign _070_[20] = logic_result[0] &(* src = "rtl/top/alu_4bit.v:0.0-0.0|rtl/top/alu_4bit.v:100.9-124.16|/usr/bin/../share/yosys/techmap.v:586.44-586.84" *)  _071_[5];
  assign _070_[21] = logic_result[1] &(* src = "rtl/top/alu_4bit.v:0.0-0.0|rtl/top/alu_4bit.v:100.9-124.16|/usr/bin/../share/yosys/techmap.v:586.44-586.84" *)  _071_[5];
  assign _070_[22] = logic_result[2] &(* src = "rtl/top/alu_4bit.v:0.0-0.0|rtl/top/alu_4bit.v:100.9-124.16|/usr/bin/../share/yosys/techmap.v:586.44-586.84" *)  _071_[5];
  assign _070_[23] = logic_result[3] &(* src = "rtl/top/alu_4bit.v:0.0-0.0|rtl/top/alu_4bit.v:100.9-124.16|/usr/bin/../share/yosys/techmap.v:586.44-586.84" *)  _071_[5];
  assign _070_[16] = _069_[16] &(* src = "rtl/top/alu_4bit.v:0.0-0.0|rtl/top/alu_4bit.v:100.9-124.16|/usr/bin/../share/yosys/techmap.v:586.44-586.84" *)  _071_[4];
  assign _070_[17] = _069_[17] &(* src = "rtl/top/alu_4bit.v:0.0-0.0|rtl/top/alu_4bit.v:100.9-124.16|/usr/bin/../share/yosys/techmap.v:586.44-586.84" *)  _071_[4];
  assign _070_[18] = _069_[18] &(* src = "rtl/top/alu_4bit.v:0.0-0.0|rtl/top/alu_4bit.v:100.9-124.16|/usr/bin/../share/yosys/techmap.v:586.44-586.84" *)  _071_[4];
  assign _070_[19] = _069_[19] &(* src = "rtl/top/alu_4bit.v:0.0-0.0|rtl/top/alu_4bit.v:100.9-124.16|/usr/bin/../share/yosys/techmap.v:586.44-586.84" *)  _071_[4];
  assign _070_[12] = _069_[12] &(* src = "rtl/top/alu_4bit.v:0.0-0.0|rtl/top/alu_4bit.v:100.9-124.16|/usr/bin/../share/yosys/techmap.v:586.44-586.84" *)  _071_[3];
  assign _070_[13] = _069_[13] &(* src = "rtl/top/alu_4bit.v:0.0-0.0|rtl/top/alu_4bit.v:100.9-124.16|/usr/bin/../share/yosys/techmap.v:586.44-586.84" *)  _071_[3];
  assign _070_[14] = _069_[14] &(* src = "rtl/top/alu_4bit.v:0.0-0.0|rtl/top/alu_4bit.v:100.9-124.16|/usr/bin/../share/yosys/techmap.v:586.44-586.84" *)  _071_[3];
  assign _070_[15] = _069_[15] &(* src = "rtl/top/alu_4bit.v:0.0-0.0|rtl/top/alu_4bit.v:100.9-124.16|/usr/bin/../share/yosys/techmap.v:586.44-586.84" *)  _071_[3];
  assign _070_[8] = _069_[8] &(* src = "rtl/top/alu_4bit.v:0.0-0.0|rtl/top/alu_4bit.v:100.9-124.16|/usr/bin/../share/yosys/techmap.v:586.44-586.84" *)  _071_[2];
  assign _070_[9] = _069_[9] &(* src = "rtl/top/alu_4bit.v:0.0-0.0|rtl/top/alu_4bit.v:100.9-124.16|/usr/bin/../share/yosys/techmap.v:586.44-586.84" *)  _071_[2];
  assign _070_[10] = _069_[10] &(* src = "rtl/top/alu_4bit.v:0.0-0.0|rtl/top/alu_4bit.v:100.9-124.16|/usr/bin/../share/yosys/techmap.v:586.44-586.84" *)  _071_[2];
  assign _070_[11] = _069_[11] &(* src = "rtl/top/alu_4bit.v:0.0-0.0|rtl/top/alu_4bit.v:100.9-124.16|/usr/bin/../share/yosys/techmap.v:586.44-586.84" *)  _071_[2];
  assign _070_[4] = shift_result[0] &(* src = "rtl/top/alu_4bit.v:0.0-0.0|rtl/top/alu_4bit.v:100.9-124.16|/usr/bin/../share/yosys/techmap.v:586.44-586.84" *)  _067_[1];
  assign _070_[5] = shift_result[1] &(* src = "rtl/top/alu_4bit.v:0.0-0.0|rtl/top/alu_4bit.v:100.9-124.16|/usr/bin/../share/yosys/techmap.v:586.44-586.84" *)  _067_[1];
  assign _070_[6] = shift_result[2] &(* src = "rtl/top/alu_4bit.v:0.0-0.0|rtl/top/alu_4bit.v:100.9-124.16|/usr/bin/../share/yosys/techmap.v:586.44-586.84" *)  _067_[1];
  assign _070_[7] = shift_result[3] &(* src = "rtl/top/alu_4bit.v:0.0-0.0|rtl/top/alu_4bit.v:100.9-124.16|/usr/bin/../share/yosys/techmap.v:586.44-586.84" *)  _067_[1];
  assign _070_[0] = a[0] &(* src = "rtl/top/alu_4bit.v:0.0-0.0|rtl/top/alu_4bit.v:100.9-124.16|/usr/bin/../share/yosys/techmap.v:586.44-586.84" *)  _071_[0];
  assign _070_[1] = a[1] &(* src = "rtl/top/alu_4bit.v:0.0-0.0|rtl/top/alu_4bit.v:100.9-124.16|/usr/bin/../share/yosys/techmap.v:586.44-586.84" *)  _071_[0];
  assign _070_[2] = a[2] &(* src = "rtl/top/alu_4bit.v:0.0-0.0|rtl/top/alu_4bit.v:100.9-124.16|/usr/bin/../share/yosys/techmap.v:586.44-586.84" *)  _071_[0];
  assign _070_[3] = a[3] &(* src = "rtl/top/alu_4bit.v:0.0-0.0|rtl/top/alu_4bit.v:100.9-124.16|/usr/bin/../share/yosys/techmap.v:586.44-586.84" *)  _071_[0];
  (* module_not_derived = 32'd1 *)
  (* src = "rtl/top/alu_4bit.v:68.16-75.6" *)
  adder_4bit u_adder (
    .a(a),
    .b(b_arith),
    .cout(arith_cout),
    .overflow(arith_overflow),
    .result(arith_result),
    .sub(sub_op)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "rtl/top/alu_4bit.v:78.16-83.6" *)
  logic_unit u_logic (
    .a(a),
    .b(b),
    .logic_op(logic_sel),
    .result(logic_result)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "rtl/top/alu_4bit.v:86.16-91.6" *)
  shift_unit u_shift (
    .a(a),
    .result(shift_result),
    .shift_op(shift_sel),
    .shift_out(shift_carry)
  );
  assign _009_[0] = _008_[0];
  assign _010_[1] = _008_[1];
  assign _011_[1] = _008_[1];
  assign _012_[1] = _009_[1];
  assign _013_[0] = _008_[0];
  assign _014_[0] = _011_[0];
  assign _016_[3] = _005_;
  assign _019_[2:0] = _016_[2:0];
  assign _020_[0] = _017_[0];
  assign _062_[0] = 1'h0;
  assign _065_[4:1] = { _052_, _051_, _053_, _050_ };
  assign _066_[0] = 1'h0;
  assign _067_[2] = _063_[1];
  assign { _069_[27:20], _069_[7:0] } = { arith_result, logic_result, shift_result, a };
  assign { _071_[6], _071_[1] } = { _063_[1], _067_[1] };
  assign _077_[1] = 1'h1;
  assign _078_[1] = _037_;
  assign result[3] = negative;
endmodule

(* src = "rtl/modules/full_adder.v:8.1-22.10" *)
module full_adder(a, b, cin, sum, cout);
  (* src = "rtl/modules/full_adder.v:20.20-20.25" *)
  wire _00_;
  (* src = "rtl/modules/full_adder.v:20.30-20.37" *)
  wire _01_;
  (* src = "rtl/modules/full_adder.v:20.42-20.49" *)
  wire _02_;
  (* src = "rtl/modules/full_adder.v:20.19-20.38" *)
  wire _03_;
  (* src = "rtl/modules/full_adder.v:17.19-17.24" *)
  wire _04_;
  (* src = "rtl/modules/full_adder.v:9.17-9.18" *)
  input a;
  wire a;
  (* src = "rtl/modules/full_adder.v:10.17-10.18" *)
  input b;
  wire b;
  (* src = "rtl/modules/full_adder.v:11.17-11.20" *)
  input cin;
  wire cin;
  (* src = "rtl/modules/full_adder.v:13.17-13.21" *)
  output cout;
  wire cout;
  (* src = "rtl/modules/full_adder.v:12.17-12.20" *)
  output sum;
  wire sum;
  assign _04_ = a ^(* src = "rtl/modules/full_adder.v:17.19-17.24" *)  b;
  assign sum = _04_ ^(* src = "rtl/modules/full_adder.v:17.19-17.30" *)  cin;
  assign _00_ = a &(* src = "rtl/modules/full_adder.v:20.20-20.25" *)  b;
  assign _01_ = b &(* src = "rtl/modules/full_adder.v:20.30-20.37" *)  cin;
  assign _03_ = _00_ |(* src = "rtl/modules/full_adder.v:20.19-20.38" *)  _01_;
  assign _02_ = a &(* src = "rtl/modules/full_adder.v:20.42-20.49" *)  cin;
  assign cout = _03_ |(* src = "rtl/modules/full_adder.v:20.19-20.50" *)  _02_;
endmodule

(* src = "rtl/modules/logic_unit.v:7.1-30.10" *)
module logic_unit(a, b, logic_op, result);
  wire _00_;
  wire _01_;
  wire [1:0] _02_;
  wire [1:0] _03_;
  wire [1:0] _04_;
  wire [1:0] _05_;
  wire [1:0] _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  (* force_downto = 32'd1 *)
  (* src = "rtl/modules/logic_unit.v:0.0-0.0|rtl/modules/logic_unit.v:21.9-27.16|/usr/bin/../share/yosys/techmap.v:572.28-572.29" *)
  wire [15:0] _11_;
  (* force_downto = 32'd1 *)
  (* src = "rtl/modules/logic_unit.v:0.0-0.0|rtl/modules/logic_unit.v:21.9-27.16|/usr/bin/../share/yosys/techmap.v:584.28-584.35" *)
  wire [15:0] _12_;
  (* force_downto = 32'd1 *)
  (* src = "rtl/modules/logic_unit.v:0.0-0.0|rtl/modules/logic_unit.v:21.9-27.16|/usr/bin/../share/yosys/techmap.v:574.22-574.23" *)
  wire [3:0] _13_;
  (* force_downto = 32'd1 *)
  (* src = "rtl/modules/logic_unit.v:0.0-0.0|rtl/modules/logic_unit.v:21.9-27.16|/usr/bin/../share/yosys/techmap.v:579.19-579.22" *)
  wire [3:0] _14_;
  (* src = "rtl/modules/logic_unit.v:0.0-0.0|rtl/modules/logic_unit.v:21.9-27.16|/usr/bin/../share/yosys/techmap.v:598.13-598.15" *)
  wire _15_;
  (* src = "rtl/modules/logic_unit.v:8.23-8.24" *)
  input [3:0] a;
  wire [3:0] a;
  (* src = "rtl/modules/logic_unit.v:9.23-9.24" *)
  input [3:0] b;
  wire [3:0] b;
  (* src = "rtl/modules/logic_unit.v:10.23-10.31" *)
  input [1:0] logic_op;
  wire [1:0] logic_op;
  (* src = "rtl/modules/logic_unit.v:11.23-11.29" *)
  output [3:0] result;
  wire [3:0] result;
  assign _01_ = ~logic_op[1];
  assign _00_ = ~logic_op[0];
  assign _08_ = _00_ |(* src = "rtl/modules/logic_unit.v:0.0-0.0|rtl/modules/logic_unit.v:21.9-27.16" *)  _01_;
  assign _09_ = logic_op[0] |(* src = "rtl/modules/logic_unit.v:0.0-0.0|rtl/modules/logic_unit.v:21.9-27.16" *)  _01_;
  assign _10_ = _00_ |(* src = "rtl/modules/logic_unit.v:0.0-0.0|rtl/modules/logic_unit.v:21.9-27.16" *)  logic_op[1];
  assign _02_[0] = _12_[3] |(* src = "rtl/modules/logic_unit.v:0.0-0.0|rtl/modules/logic_unit.v:21.9-27.16|/usr/bin/../share/yosys/techmap.v:594.20-594.31" *)  _12_[7];
  assign _02_[1] = _12_[11] |(* src = "rtl/modules/logic_unit.v:0.0-0.0|rtl/modules/logic_unit.v:21.9-27.16|/usr/bin/../share/yosys/techmap.v:594.20-594.31" *)  _12_[15];
  assign _14_[3] = _02_[0] |(* src = "rtl/modules/logic_unit.v:0.0-0.0|rtl/modules/logic_unit.v:21.9-27.16|/usr/bin/../share/yosys/techmap.v:594.20-594.31" *)  _02_[1];
  assign _03_[0] = _12_[2] |(* src = "rtl/modules/logic_unit.v:0.0-0.0|rtl/modules/logic_unit.v:21.9-27.16|/usr/bin/../share/yosys/techmap.v:594.20-594.31" *)  _12_[6];
  assign _03_[1] = _12_[10] |(* src = "rtl/modules/logic_unit.v:0.0-0.0|rtl/modules/logic_unit.v:21.9-27.16|/usr/bin/../share/yosys/techmap.v:594.20-594.31" *)  _12_[14];
  assign _14_[2] = _03_[0] |(* src = "rtl/modules/logic_unit.v:0.0-0.0|rtl/modules/logic_unit.v:21.9-27.16|/usr/bin/../share/yosys/techmap.v:594.20-594.31" *)  _03_[1];
  assign _04_[0] = _12_[1] |(* src = "rtl/modules/logic_unit.v:0.0-0.0|rtl/modules/logic_unit.v:21.9-27.16|/usr/bin/../share/yosys/techmap.v:594.20-594.31" *)  _12_[5];
  assign _04_[1] = _12_[9] |(* src = "rtl/modules/logic_unit.v:0.0-0.0|rtl/modules/logic_unit.v:21.9-27.16|/usr/bin/../share/yosys/techmap.v:594.20-594.31" *)  _12_[13];
  assign _14_[1] = _04_[0] |(* src = "rtl/modules/logic_unit.v:0.0-0.0|rtl/modules/logic_unit.v:21.9-27.16|/usr/bin/../share/yosys/techmap.v:594.20-594.31" *)  _04_[1];
  assign _05_[0] = _12_[0] |(* src = "rtl/modules/logic_unit.v:0.0-0.0|rtl/modules/logic_unit.v:21.9-27.16|/usr/bin/../share/yosys/techmap.v:594.20-594.31" *)  _12_[4];
  assign _05_[1] = _12_[8] |(* src = "rtl/modules/logic_unit.v:0.0-0.0|rtl/modules/logic_unit.v:21.9-27.16|/usr/bin/../share/yosys/techmap.v:594.20-594.31" *)  _12_[12];
  assign _14_[0] = _05_[0] |(* src = "rtl/modules/logic_unit.v:0.0-0.0|rtl/modules/logic_unit.v:21.9-27.16|/usr/bin/../share/yosys/techmap.v:594.20-594.31" *)  _05_[1];
  assign _06_[0] = _13_[0] |(* src = "rtl/modules/logic_unit.v:0.0-0.0|rtl/modules/logic_unit.v:21.9-27.16|/usr/bin/../share/yosys/techmap.v:598.13-598.15" *)  _13_[1];
  assign _06_[1] = _13_[2] |(* src = "rtl/modules/logic_unit.v:0.0-0.0|rtl/modules/logic_unit.v:21.9-27.16|/usr/bin/../share/yosys/techmap.v:598.13-598.15" *)  _13_[3];
  assign _15_ = _06_[0] |(* src = "rtl/modules/logic_unit.v:0.0-0.0|rtl/modules/logic_unit.v:21.9-27.16|/usr/bin/../share/yosys/techmap.v:598.13-598.15" *)  _06_[1];
  assign _07_ = logic_op[0] |(* src = "rtl/modules/logic_unit.v:0.0-0.0|rtl/modules/logic_unit.v:21.9-27.16" *)  logic_op[1];
  assign _13_[0] = ~(* src = "rtl/modules/logic_unit.v:0.0-0.0|rtl/modules/logic_unit.v:21.9-27.16" *) _08_;
  assign _13_[1] = ~(* src = "rtl/modules/logic_unit.v:0.0-0.0|rtl/modules/logic_unit.v:21.9-27.16" *) _09_;
  assign _13_[2] = ~(* src = "rtl/modules/logic_unit.v:0.0-0.0|rtl/modules/logic_unit.v:21.9-27.16" *) _10_;
  assign _13_[3] = ~(* src = "rtl/modules/logic_unit.v:0.0-0.0|rtl/modules/logic_unit.v:21.9-27.16" *) _07_;
  assign result[0] = _15_ ? (* src = "rtl/modules/logic_unit.v:0.0-0.0|rtl/modules/logic_unit.v:21.9-27.16|/usr/bin/../share/yosys/techmap.v:598.13-598.25" *) _14_[0] : 1'hx;
  assign result[1] = _15_ ? (* src = "rtl/modules/logic_unit.v:0.0-0.0|rtl/modules/logic_unit.v:21.9-27.16|/usr/bin/../share/yosys/techmap.v:598.13-598.25" *) _14_[1] : 1'hx;
  assign result[2] = _15_ ? (* src = "rtl/modules/logic_unit.v:0.0-0.0|rtl/modules/logic_unit.v:21.9-27.16|/usr/bin/../share/yosys/techmap.v:598.13-598.25" *) _14_[2] : 1'hx;
  assign result[3] = _15_ ? (* src = "rtl/modules/logic_unit.v:0.0-0.0|rtl/modules/logic_unit.v:21.9-27.16|/usr/bin/../share/yosys/techmap.v:598.13-598.25" *) _14_[3] : 1'hx;
  assign _11_[0] = ~(* src = "rtl/modules/logic_unit.v:25.31-25.33" *) a[0];
  assign _11_[1] = ~(* src = "rtl/modules/logic_unit.v:25.31-25.33" *) a[1];
  assign _11_[2] = ~(* src = "rtl/modules/logic_unit.v:25.31-25.33" *) a[2];
  assign _11_[3] = ~(* src = "rtl/modules/logic_unit.v:25.31-25.33" *) a[3];
  assign _11_[12] = a[0] &(* src = "rtl/modules/logic_unit.v:22.31-22.36" *)  b[0];
  assign _11_[13] = a[1] &(* src = "rtl/modules/logic_unit.v:22.31-22.36" *)  b[1];
  assign _11_[14] = a[2] &(* src = "rtl/modules/logic_unit.v:22.31-22.36" *)  b[2];
  assign _11_[15] = a[3] &(* src = "rtl/modules/logic_unit.v:22.31-22.36" *)  b[3];
  assign _11_[8] = a[0] |(* src = "rtl/modules/logic_unit.v:23.31-23.36" *)  b[0];
  assign _11_[9] = a[1] |(* src = "rtl/modules/logic_unit.v:23.31-23.36" *)  b[1];
  assign _11_[10] = a[2] |(* src = "rtl/modules/logic_unit.v:23.31-23.36" *)  b[2];
  assign _11_[11] = a[3] |(* src = "rtl/modules/logic_unit.v:23.31-23.36" *)  b[3];
  assign _11_[4] = a[0] ^(* src = "rtl/modules/logic_unit.v:24.31-24.36" *)  b[0];
  assign _11_[5] = a[1] ^(* src = "rtl/modules/logic_unit.v:24.31-24.36" *)  b[1];
  assign _11_[6] = a[2] ^(* src = "rtl/modules/logic_unit.v:24.31-24.36" *)  b[2];
  assign _11_[7] = a[3] ^(* src = "rtl/modules/logic_unit.v:24.31-24.36" *)  b[3];
  assign _12_[12] = _11_[12] &(* src = "rtl/modules/logic_unit.v:0.0-0.0|rtl/modules/logic_unit.v:21.9-27.16|/usr/bin/../share/yosys/techmap.v:586.44-586.84" *)  _13_[3];
  assign _12_[13] = _11_[13] &(* src = "rtl/modules/logic_unit.v:0.0-0.0|rtl/modules/logic_unit.v:21.9-27.16|/usr/bin/../share/yosys/techmap.v:586.44-586.84" *)  _13_[3];
  assign _12_[14] = _11_[14] &(* src = "rtl/modules/logic_unit.v:0.0-0.0|rtl/modules/logic_unit.v:21.9-27.16|/usr/bin/../share/yosys/techmap.v:586.44-586.84" *)  _13_[3];
  assign _12_[15] = _11_[15] &(* src = "rtl/modules/logic_unit.v:0.0-0.0|rtl/modules/logic_unit.v:21.9-27.16|/usr/bin/../share/yosys/techmap.v:586.44-586.84" *)  _13_[3];
  assign _12_[8] = _11_[8] &(* src = "rtl/modules/logic_unit.v:0.0-0.0|rtl/modules/logic_unit.v:21.9-27.16|/usr/bin/../share/yosys/techmap.v:586.44-586.84" *)  _13_[2];
  assign _12_[9] = _11_[9] &(* src = "rtl/modules/logic_unit.v:0.0-0.0|rtl/modules/logic_unit.v:21.9-27.16|/usr/bin/../share/yosys/techmap.v:586.44-586.84" *)  _13_[2];
  assign _12_[10] = _11_[10] &(* src = "rtl/modules/logic_unit.v:0.0-0.0|rtl/modules/logic_unit.v:21.9-27.16|/usr/bin/../share/yosys/techmap.v:586.44-586.84" *)  _13_[2];
  assign _12_[11] = _11_[11] &(* src = "rtl/modules/logic_unit.v:0.0-0.0|rtl/modules/logic_unit.v:21.9-27.16|/usr/bin/../share/yosys/techmap.v:586.44-586.84" *)  _13_[2];
  assign _12_[4] = _11_[4] &(* src = "rtl/modules/logic_unit.v:0.0-0.0|rtl/modules/logic_unit.v:21.9-27.16|/usr/bin/../share/yosys/techmap.v:586.44-586.84" *)  _13_[1];
  assign _12_[5] = _11_[5] &(* src = "rtl/modules/logic_unit.v:0.0-0.0|rtl/modules/logic_unit.v:21.9-27.16|/usr/bin/../share/yosys/techmap.v:586.44-586.84" *)  _13_[1];
  assign _12_[6] = _11_[6] &(* src = "rtl/modules/logic_unit.v:0.0-0.0|rtl/modules/logic_unit.v:21.9-27.16|/usr/bin/../share/yosys/techmap.v:586.44-586.84" *)  _13_[1];
  assign _12_[7] = _11_[7] &(* src = "rtl/modules/logic_unit.v:0.0-0.0|rtl/modules/logic_unit.v:21.9-27.16|/usr/bin/../share/yosys/techmap.v:586.44-586.84" *)  _13_[1];
  assign _12_[0] = _11_[0] &(* src = "rtl/modules/logic_unit.v:0.0-0.0|rtl/modules/logic_unit.v:21.9-27.16|/usr/bin/../share/yosys/techmap.v:586.44-586.84" *)  _13_[0];
  assign _12_[1] = _11_[1] &(* src = "rtl/modules/logic_unit.v:0.0-0.0|rtl/modules/logic_unit.v:21.9-27.16|/usr/bin/../share/yosys/techmap.v:586.44-586.84" *)  _13_[0];
  assign _12_[2] = _11_[2] &(* src = "rtl/modules/logic_unit.v:0.0-0.0|rtl/modules/logic_unit.v:21.9-27.16|/usr/bin/../share/yosys/techmap.v:586.44-586.84" *)  _13_[0];
  assign _12_[3] = _11_[3] &(* src = "rtl/modules/logic_unit.v:0.0-0.0|rtl/modules/logic_unit.v:21.9-27.16|/usr/bin/../share/yosys/techmap.v:586.44-586.84" *)  _13_[0];
endmodule

(* src = "rtl/modules/shift_unit.v:7.1-45.10" *)
module shift_unit(a, shift_op, result, shift_out);
  wire _00_;
  wire _01_;
  wire [1:0] _02_;
  wire [1:0] _03_;
  wire [1:0] _04_;
  wire [1:0] _05_;
  wire [1:0] _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  (* force_downto = 32'd1 *)
  (* src = "rtl/modules/shift_unit.v:0.0-0.0|rtl/modules/shift_unit.v:21.9-42.16|/usr/bin/../share/yosys/techmap.v:584.28-584.35" *)
  wire [1:0] _11_;
  (* force_downto = 32'd1 *)
  (* src = "rtl/modules/shift_unit.v:0.0-0.0|rtl/modules/shift_unit.v:21.9-42.16|/usr/bin/../share/yosys/techmap.v:574.22-574.23" *)
  wire [1:0] _12_;
  (* force_downto = 32'd1 *)
  (* src = "rtl/modules/shift_unit.v:0.0-0.0|rtl/modules/shift_unit.v:21.9-42.16|/usr/bin/../share/yosys/techmap.v:579.19-579.22" *)
  wire _13_;
  (* force_downto = 32'd1 *)
  (* src = "rtl/modules/shift_unit.v:0.0-0.0|rtl/modules/shift_unit.v:21.9-42.16|/usr/bin/../share/yosys/techmap.v:584.28-584.35" *)
  wire [15:0] _14_;
  (* force_downto = 32'd1 *)
  (* src = "rtl/modules/shift_unit.v:0.0-0.0|rtl/modules/shift_unit.v:21.9-42.16|/usr/bin/../share/yosys/techmap.v:574.22-574.23" *)
  wire [3:0] _15_;
  (* force_downto = 32'd1 *)
  (* src = "rtl/modules/shift_unit.v:0.0-0.0|rtl/modules/shift_unit.v:21.9-42.16|/usr/bin/../share/yosys/techmap.v:579.19-579.22" *)
  wire [3:0] _16_;
  (* src = "rtl/modules/shift_unit.v:0.0-0.0|rtl/modules/shift_unit.v:21.9-42.16|/usr/bin/../share/yosys/techmap.v:598.13-598.15" *)
  wire _17_;
  (* src = "rtl/modules/shift_unit.v:0.0-0.0|rtl/modules/shift_unit.v:21.9-42.16|/usr/bin/../share/yosys/techmap.v:598.13-598.15" *)
  wire _18_;
  (* src = "rtl/modules/shift_unit.v:8.23-8.24" *)
  input [3:0] a;
  wire [3:0] a;
  (* src = "rtl/modules/shift_unit.v:10.23-10.29" *)
  output [3:0] result;
  wire [3:0] result;
  (* src = "rtl/modules/shift_unit.v:9.23-9.31" *)
  input [1:0] shift_op;
  wire [1:0] shift_op;
  (* src = "rtl/modules/shift_unit.v:11.23-11.32" *)
  output shift_out;
  wire shift_out;
  assign _00_ = ~shift_op[1];
  assign _01_ = ~shift_op[0];
  assign _12_[1] = _15_[1] |(* src = {0{1'b0}} *)  _15_[2];
  assign _12_[0] = _15_[0] |(* src = {0{1'b0}} *)  _15_[3];
  assign _08_ = _01_ |(* src = "rtl/modules/shift_unit.v:0.0-0.0|rtl/modules/shift_unit.v:21.9-42.16" *)  _00_;
  assign _09_ = shift_op[0] |(* src = "rtl/modules/shift_unit.v:0.0-0.0|rtl/modules/shift_unit.v:21.9-42.16" *)  _00_;
  assign _10_ = _01_ |(* src = "rtl/modules/shift_unit.v:0.0-0.0|rtl/modules/shift_unit.v:21.9-42.16" *)  shift_op[1];
  assign _13_ = _11_[0] |(* src = "rtl/modules/shift_unit.v:0.0-0.0|rtl/modules/shift_unit.v:21.9-42.16|/usr/bin/../share/yosys/techmap.v:594.20-594.31" *)  _11_[1];
  assign _17_ = _12_[0] |(* src = "rtl/modules/shift_unit.v:0.0-0.0|rtl/modules/shift_unit.v:21.9-42.16|/usr/bin/../share/yosys/techmap.v:598.13-598.15" *)  _12_[1];
  assign _02_[0] = _14_[3] |(* src = "rtl/modules/shift_unit.v:0.0-0.0|rtl/modules/shift_unit.v:21.9-42.16|/usr/bin/../share/yosys/techmap.v:594.20-594.31" *)  _14_[7];
  assign _16_[3] = _02_[0] |(* src = "rtl/modules/shift_unit.v:0.0-0.0|rtl/modules/shift_unit.v:21.9-42.16|/usr/bin/../share/yosys/techmap.v:594.20-594.31" *)  _14_[15];
  assign _03_[0] = _14_[2] |(* src = "rtl/modules/shift_unit.v:0.0-0.0|rtl/modules/shift_unit.v:21.9-42.16|/usr/bin/../share/yosys/techmap.v:594.20-594.31" *)  _14_[7];
  assign _03_[1] = _14_[10] |(* src = "rtl/modules/shift_unit.v:0.0-0.0|rtl/modules/shift_unit.v:21.9-42.16|/usr/bin/../share/yosys/techmap.v:594.20-594.31" *)  _14_[14];
  assign _16_[2] = _03_[0] |(* src = "rtl/modules/shift_unit.v:0.0-0.0|rtl/modules/shift_unit.v:21.9-42.16|/usr/bin/../share/yosys/techmap.v:594.20-594.31" *)  _03_[1];
  assign _04_[0] = _14_[1] |(* src = "rtl/modules/shift_unit.v:0.0-0.0|rtl/modules/shift_unit.v:21.9-42.16|/usr/bin/../share/yosys/techmap.v:594.20-594.31" *)  _14_[5];
  assign _04_[1] = _14_[9] |(* src = "rtl/modules/shift_unit.v:0.0-0.0|rtl/modules/shift_unit.v:21.9-42.16|/usr/bin/../share/yosys/techmap.v:594.20-594.31" *)  _14_[13];
  assign _16_[1] = _04_[0] |(* src = "rtl/modules/shift_unit.v:0.0-0.0|rtl/modules/shift_unit.v:21.9-42.16|/usr/bin/../share/yosys/techmap.v:594.20-594.31" *)  _04_[1];
  assign _05_[0] = _14_[0] |(* src = "rtl/modules/shift_unit.v:0.0-0.0|rtl/modules/shift_unit.v:21.9-42.16|/usr/bin/../share/yosys/techmap.v:594.20-594.31" *)  _14_[4];
  assign _16_[0] = _05_[0] |(* src = "rtl/modules/shift_unit.v:0.0-0.0|rtl/modules/shift_unit.v:21.9-42.16|/usr/bin/../share/yosys/techmap.v:594.20-594.31" *)  _14_[8];
  assign _06_[0] = _15_[0] |(* src = "rtl/modules/shift_unit.v:0.0-0.0|rtl/modules/shift_unit.v:21.9-42.16|/usr/bin/../share/yosys/techmap.v:598.13-598.15" *)  _15_[1];
  assign _06_[1] = _15_[2] |(* src = "rtl/modules/shift_unit.v:0.0-0.0|rtl/modules/shift_unit.v:21.9-42.16|/usr/bin/../share/yosys/techmap.v:598.13-598.15" *)  _15_[3];
  assign _18_ = _06_[0] |(* src = "rtl/modules/shift_unit.v:0.0-0.0|rtl/modules/shift_unit.v:21.9-42.16|/usr/bin/../share/yosys/techmap.v:598.13-598.15" *)  _06_[1];
  assign _07_ = shift_op[0] |(* src = "rtl/modules/shift_unit.v:0.0-0.0|rtl/modules/shift_unit.v:21.9-42.16" *)  shift_op[1];
  assign _15_[0] = ~(* src = "rtl/modules/shift_unit.v:0.0-0.0|rtl/modules/shift_unit.v:21.9-42.16" *) _08_;
  assign _15_[1] = ~(* src = "rtl/modules/shift_unit.v:0.0-0.0|rtl/modules/shift_unit.v:21.9-42.16" *) _09_;
  assign _15_[2] = ~(* src = "rtl/modules/shift_unit.v:0.0-0.0|rtl/modules/shift_unit.v:21.9-42.16" *) _10_;
  assign _15_[3] = ~(* src = "rtl/modules/shift_unit.v:0.0-0.0|rtl/modules/shift_unit.v:21.9-42.16" *) _07_;
  assign shift_out = _17_ ? (* src = "rtl/modules/shift_unit.v:0.0-0.0|rtl/modules/shift_unit.v:21.9-42.16|/usr/bin/../share/yosys/techmap.v:598.13-598.25" *) _13_ : 1'hx;
  assign result[0] = _18_ ? (* src = "rtl/modules/shift_unit.v:0.0-0.0|rtl/modules/shift_unit.v:21.9-42.16|/usr/bin/../share/yosys/techmap.v:598.13-598.25" *) _16_[0] : 1'hx;
  assign result[1] = _18_ ? (* src = "rtl/modules/shift_unit.v:0.0-0.0|rtl/modules/shift_unit.v:21.9-42.16|/usr/bin/../share/yosys/techmap.v:598.13-598.25" *) _16_[1] : 1'hx;
  assign result[2] = _18_ ? (* src = "rtl/modules/shift_unit.v:0.0-0.0|rtl/modules/shift_unit.v:21.9-42.16|/usr/bin/../share/yosys/techmap.v:598.13-598.25" *) _16_[2] : 1'hx;
  assign result[3] = _18_ ? (* src = "rtl/modules/shift_unit.v:0.0-0.0|rtl/modules/shift_unit.v:21.9-42.16|/usr/bin/../share/yosys/techmap.v:598.13-598.25" *) _16_[3] : 1'hx;
  assign _11_[1] = a[0] &(* src = "rtl/modules/shift_unit.v:0.0-0.0|rtl/modules/shift_unit.v:21.9-42.16|/usr/bin/../share/yosys/techmap.v:586.44-586.84" *)  _12_[1];
  assign _11_[0] = a[3] &(* src = "rtl/modules/shift_unit.v:0.0-0.0|rtl/modules/shift_unit.v:21.9-42.16|/usr/bin/../share/yosys/techmap.v:586.44-586.84" *)  _12_[0];
  assign _14_[13] = a[0] &(* src = "rtl/modules/shift_unit.v:0.0-0.0|rtl/modules/shift_unit.v:21.9-42.16|/usr/bin/../share/yosys/techmap.v:586.44-586.84" *)  _15_[3];
  assign _14_[14] = a[1] &(* src = "rtl/modules/shift_unit.v:0.0-0.0|rtl/modules/shift_unit.v:21.9-42.16|/usr/bin/../share/yosys/techmap.v:586.44-586.84" *)  _15_[3];
  assign _14_[15] = a[2] &(* src = "rtl/modules/shift_unit.v:0.0-0.0|rtl/modules/shift_unit.v:21.9-42.16|/usr/bin/../share/yosys/techmap.v:586.44-586.84" *)  _15_[3];
  assign _14_[8] = a[1] &(* src = "rtl/modules/shift_unit.v:0.0-0.0|rtl/modules/shift_unit.v:21.9-42.16|/usr/bin/../share/yosys/techmap.v:586.44-586.84" *)  _15_[2];
  assign _14_[9] = a[2] &(* src = "rtl/modules/shift_unit.v:0.0-0.0|rtl/modules/shift_unit.v:21.9-42.16|/usr/bin/../share/yosys/techmap.v:586.44-586.84" *)  _15_[2];
  assign _14_[10] = a[3] &(* src = "rtl/modules/shift_unit.v:0.0-0.0|rtl/modules/shift_unit.v:21.9-42.16|/usr/bin/../share/yosys/techmap.v:586.44-586.84" *)  _15_[2];
  assign _14_[4] = a[1] &(* src = "rtl/modules/shift_unit.v:0.0-0.0|rtl/modules/shift_unit.v:21.9-42.16|/usr/bin/../share/yosys/techmap.v:586.44-586.84" *)  _15_[1];
  assign _14_[5] = a[2] &(* src = "rtl/modules/shift_unit.v:0.0-0.0|rtl/modules/shift_unit.v:21.9-42.16|/usr/bin/../share/yosys/techmap.v:586.44-586.84" *)  _15_[1];
  assign _14_[7] = a[3] &(* src = "rtl/modules/shift_unit.v:0.0-0.0|rtl/modules/shift_unit.v:21.9-42.16|/usr/bin/../share/yosys/techmap.v:586.44-586.84" *)  _15_[1];
  assign _14_[0] = a[3] &(* src = "rtl/modules/shift_unit.v:0.0-0.0|rtl/modules/shift_unit.v:21.9-42.16|/usr/bin/../share/yosys/techmap.v:586.44-586.84" *)  _15_[0];
  assign _14_[1] = a[0] &(* src = "rtl/modules/shift_unit.v:0.0-0.0|rtl/modules/shift_unit.v:21.9-42.16|/usr/bin/../share/yosys/techmap.v:586.44-586.84" *)  _15_[0];
  assign _14_[2] = a[1] &(* src = "rtl/modules/shift_unit.v:0.0-0.0|rtl/modules/shift_unit.v:21.9-42.16|/usr/bin/../share/yosys/techmap.v:586.44-586.84" *)  _15_[0];
  assign _14_[3] = a[2] &(* src = "rtl/modules/shift_unit.v:0.0-0.0|rtl/modules/shift_unit.v:21.9-42.16|/usr/bin/../share/yosys/techmap.v:586.44-586.84" *)  _15_[0];
  assign _02_[1] = _14_[15];
  assign _05_[1] = _14_[8];
  assign { _14_[12:11], _14_[6] } = { 2'h0, _14_[7] };
endmodule
